import {
  AngularMaterialTool,
  AngularTool,
  AntDTool,
  ApolloClient,
  AxiosTool,
  CustomStylingTool,
  FigmaTool,
  FormikTool,
  GithubTool,
  GraphQL,
  JavascriptTool,
  Jest,
  JiraTool,
  MaterialUITool,
  NgRxTool,
  ReactHookFormTool,
  ReactTestingLibrary,
  ReactTool,
  ReduxTool,
  RESTTool,
  SendBirdTool,
  StyledComponentsTool,
  TailWindCSSTool,
  TanstackQueryTool,
  TypescriptTool,
  YupTool,
  ZodTool,
} from "@/features/tool/api/tools";

export const PROJECTS = [
  {
    id: 1,
    title: "Hive",
    description:
      "Health Information Network created to manage misleading information that appears in public spaces during epidemics using machine learning",
    keyPoints: [],
    tools: [
      JavascriptTool,
      TypescriptTool,
      ReactTool,
      ReduxTool,
      SendBirdTool,
      FormikTool,
      YupTool,
      StyledComponentsTool,
      AntDTool,
      AxiosTool,
      ApolloClient,
      GraphQL,
      ReactTestingLibrary,
      Jest,
      FigmaTool,
      JiraTool,
    ],
  },
  {
    id: 2,
    title: "Vanilla",
    description:
      "Platform used to build a Document Generation product, enabling admins to create and publish document packages that can be purchased by an end client",
    keyPoints: [],
    tools: [
      JavascriptTool,
      TypescriptTool,
      ReactTool,
      StyledComponentsTool,
      CustomStylingTool,
      AxiosTool,
      RESTTool,
      ReactTestingLibrary,
      Jest,
      FigmaTool,
      GithubTool,
    ],
  },
  {
    id: 3,
    title: "SchoolGig",
    keyPoints: [],
    description:
      "Platform used by schools to better engage with their employees and to provide job offers, helping them in choosing the right candidate",
    tools: [
      JavascriptTool,
      TypescriptTool,
      AngularTool,
      NgRxTool,
      ReactTool,
      ReactTestingLibrary,
      Jest,
      FigmaTool,
      GithubTool,
    ],
  },
  {
    id: 4,
    title: "LCI",
    keyPoints: [],
    description:
      "Platform for the entire suite of LCI products and their associated systems. This transformation involves the utilization of cloud-based solutions that can easily be expanded and seamlessly integrated, ensuring the delivery of secure and scalable services to clients.",
    tools: [
      JavascriptTool,
      TypescriptTool,
      ReactTool,
      TanstackQueryTool,
      ReactHookFormTool,
      ZodTool,
      MaterialUITool,
      ReactTestingLibrary,
      Jest,
      FigmaTool,
      GithubTool,
    ],
  },
];
