import {
  AngularMaterialTool,
  AngularTool,
  AntDTool,
  ApolloClient,
  AWSTool,
  AxiosTool,
  AzureTool,
  CustomStylingTool,
  FigmaTool,
  FormikTool,
  GithubTool,
  GraphQL,
  JavascriptTool,
  JestTool,
  JiraTool,
  MaterialUITool,
  NgRxTool,
  ReactHookFormTool,
  ReactTestingLibraryTool,
  ReactTool,
  ReduxTool,
  RESTTool,
  SendBirdTool,
  StyledComponentsTool,
  TailWindCSSTool,
  TanstackQueryTool,
  TypescriptTool,
  YupTool,
  ZodTool,
} from "@/features/tool/api/tools";

export const HiveTools = [
  JavascriptTool,
  TypescriptTool,
  ReactTool,
  ReduxTool,
  SendBirdTool,
  FormikTool,
  YupTool,
  StyledComponentsTool,
  AntDTool,
  AxiosTool,
  ApolloClient,
  GraphQL,
  ReactTestingLibraryTool,
  JestTool,
  FigmaTool,
  AzureTool,
  JiraTool,
];

export const VanillaTools = [
  JavascriptTool,
  TypescriptTool,
  ReactTool,
  ReduxTool,
  FormikTool,
  YupTool,
  StyledComponentsTool,
  CustomStylingTool,
  AxiosTool,
  ApolloClient,
  GraphQL,
  ReactTestingLibraryTool,
  JestTool,
  FigmaTool,
  GithubTool,
];

export const SchoolGigTools = [
  JavascriptTool,
  TypescriptTool,
  ReactTool,
  ReduxTool,
  AngularTool,
  NgRxTool,
  AngularMaterialTool,
  RESTTool,
  ReactTestingLibraryTool,
  JestTool,
  FigmaTool,
  GithubTool,
];

export const LCITools = [
  JavascriptTool,
  TypescriptTool,
  ReactTool,
  TanstackQueryTool,
  ReactHookFormTool,
  ZodTool,
  MaterialUITool,
  TailWindCSSTool,
  ReactTestingLibraryTool,
  JestTool,
  FigmaTool,
  GithubTool,
  AWSTool,
];
